# Generated by Django 6.1.1 on 2026-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
